### ISSUE TITLE
non-accessible items

### ISSUE THREAD

**Issue by Falconier** [Neceros/SRTS-Expanded#1]
It would seem that there is an issue when you land back at home base, where none of the items are accessible from the ships. I would be interested in helping as I have a strong grip on the C# language, if you would allow me to help. @Neceros

**Comment by Neceros** [comment]
Thanks, and please. 

I'm okay at C#, but not well enough to do that. The items are put into the inventories of the pawns on ship, and I would love to take them from that and put them back into the transporter's inventory, so they plop out onto the ground when you land at home.

What do you think?

**Comment by Falconier** [comment]
I agree. That would be optimal, for 'fluency' between the vanilla transport pods and the SRTSs. I will see what I can uncover.

If you have any comments or documentation I would be very grateful to have that. I will continue to update the branch as I work with the code and through some of the issues.
