### ISSUE TITLE
Bombardment and ia cores

### ISSUE THREAD

**Issue by Antoine2357** [Neceros/SRTS-Expanded#22]
Hello! 

I have a slightly embarrassing little problem.

When I bomb a target, when the ship leaves the map and comes back, it leaves behind an AI core. It's supposed to be very rare and hard to get, so it's not very good for immersion.  41 AI cores ! What the hell !! 

and sometimes the ship is blocked at the exit of the map, always when I want to bomb.

Also, wouldn't it be better to consider the ammunition as fuel, and let the colonists reload the ship automatically rather than selecting the shells each time ? 

In any case, excellent work !

Translated with www.DeepL.com/Translator (free version)

**Comment by Neceros** [comment]
Please use this version: https://github.com/Neceros/SRTS-Expanded/releases/tag/1.3.0

You have an outdated copy
