### ISSUE TITLE
 Superpods and other "ships" not launching with items loaded

### ISSUE THREAD

**Issue by ShiroiOkami11** [Neceros/SRTS-Expanded#8]
Hello man i'm a player of Rimworld non-steam i tried contact you in steam but i'm new and don't know how to use the platform(yet). As the tittle says, my superpods and other ships don't launch with items loaded, they just allow me to launch with colonist with no itens,

**Comment by twistedpolitiks** [comment]
I am also experiencing the same issue as ShiroiOkami11. When my ships are loaded with items, they will not launch. Loading them with just pawns still works though. I have since had to revert back to the December 5th release of this mod.

**Comment by Neceros** [comment]
Ah sorry about that. We've been using this as a nightly update between the devs. It's not entirely stable. Here's a link to a stable release: https://github.com/Neceros/SRTS-Expanded/tree/9a481b2738d923c0a608e771426f47e85e39c4da

Sorry!
